theme: minima
title: "Statistics snippets"
author: "Nora Wickelmaier"
description: "In this blog, I collect random scripts from questions discussed during statistics consulting."
markdown: kramdown
kramdown:
  math_engine: mathjax
