theme: minima
title: "Statistics snippets"
author: "Nora Wickelmaier"
description: "I collect random scripts here, that I use for teaching or created for questions discussed during statistics consulting."
markdown: kramdown
kramdown:
  math_engine: mathjax
